### ISSUE TITLE
Proposal: rename "Description" to "Purpose"

### ISSUE THREAD

**Issue by mploed** [ddd-crew/bounded-context-canvas#24]
In recent workshops with customers I often renamed the Description field of the canvas to "Purpose" following some content seen in the DDD community like:

_"A Bounded Context is a boundary for a model expressed in a consistent ubiquitous language tailored around a specific **purpose**"_

or 
_"A Bounded Context is a unit of Autonomy, Mastery and **Purpose**"_ (from one of Alberto's presentations)

I like making the purpose very explicit because "Description" can be interpreted as something very vague.

What do you think?

**Comment by heimeshoff** [comment]
Purpose instead of description is much more fitting, absolutely. I would stick with the first quote though, because the second one about Autonomy, Mastery, and Purpose (specifically this triad) is known to be the main motivational forces from Daniel Pinks "Drive". Besides beeing associated weirdly, I don't think that it delivers a better or more fitting definition or description of a bounded context. Master for example is not necessarily bound by the context.

**Comment by morcs** [comment]
I agree :) "Purpose" tells me much more clearly what I should be writing in that box!

**Comment by mploed** [comment]
@heimeshoff I'm aware of "Drive" and the parallel which Alberto drew... Just used it as an example that the term "purpose" appears regularly with regards to Bounded Contexts.

**Comment by NTCoding** [comment]
Hey everyone. I'm all in "purpose". It's a much better fit. Let's do it.

**Comment by mploed** [comment]
I'd create a pull request then!
